import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // ── Stitch "L'Érudition" Material 3 palette ──
        surface: "#f9f9f9",
        "surface-dim": "#dadada",
        "surface-bright": "#f9f9f9",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f3f4",
        "surface-container": "#eeeeee",
        "surface-container-high": "#e8e8e8",
        "surface-container-highest": "#e2e2e2",
        "surface-variant": "#e2e2e2",
        "on-surface": "#1a1c1c",
        "on-surface-variant": "#4e453c",
        "inverse-surface": "#2f3131",
        "inverse-on-surface": "#f0f1f1",
        outline: "#7f756b",
        "outline-variant": "#d1c4b8",
        "surface-tint": "#715a3d",
        primary: "#6f583b",
        "on-primary": "#ffffff",
        "primary-container": "#897051",
        "on-primary-container": "#fffbff",
        "inverse-primary": "#e0c29e",
        secondary: "#6a5c4d",
        "on-secondary": "#ffffff",
        "secondary-container": "#f3dfcc",
        "on-secondary-container": "#706253",
        tertiary: "#5f5c53",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#78746b",
        "on-tertiary-container": "#fffbff",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#fdddb8",
        "primary-fixed-dim": "#e0c29e",
        "on-primary-fixed": "#281803",
        "on-primary-fixed-variant": "#584328",
        "secondary-fixed": "#f3dfcc",
        "secondary-fixed-dim": "#d6c3b1",
        "on-secondary-fixed": "#241a0e",
        "on-secondary-fixed-variant": "#514537",
        "tertiary-fixed": "#e8e2d7",
        "tertiary-fixed-dim": "#cbc6bb",
        "on-tertiary-fixed": "#1d1b15",
        "on-tertiary-fixed-variant": "#4a473f",
        background: "#f9f9f9",
        "on-background": "#1a1c1c",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        unit: "8px",
        gutter: "24px",
        "margin-mobile": "20px",
        "margin-desktop": "64px",
        "container-max": "1200px",
      },
      maxWidth: {
        "container-max": "1200px",
      },
      fontFamily: {
        "display-xl": ["var(--font-hanken)", "Hanken Grotesk", "sans-serif"],
        "headline-lg": ["var(--font-hanken)", "Hanken Grotesk", "sans-serif"],
        "headline-lg-mobile": ["var(--font-hanken)", "Hanken Grotesk", "sans-serif"],
        "body-rt": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-sm": ["var(--font-inter)", "Inter", "sans-serif"],
        "code-md": ["var(--font-jbm)", "JetBrains Mono", "monospace"],
        sans: ["var(--font-inter)", "Inter", "sans-serif"],
        mono: ["var(--font-jbm)", "JetBrains Mono", "monospace"],
      },
      fontSize: {
        "body-sm": ["14px", { lineHeight: "1.5", letterSpacing: "0", fontWeight: "400" }],
        "code-md": ["14px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-rt": ["17px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "display-xl": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

export default config;
