import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // ── Palette « Atelier » : papier chaud, vert sapin, souci (accent) ──
        surface: "#fbf6ee",
        "surface-dim": "#e6dccd",
        "surface-bright": "#fffcf7",
        "surface-container-lowest": "#fffcf7",
        "surface-container-low": "#f6efe3",
        "surface-container": "#f0e6d6",
        "surface-container-high": "#e9ddca",
        "surface-container-highest": "#e2d4be",
        "surface-variant": "#ece2d2",
        "on-surface": "#2b2119",
        "on-surface-variant": "#66574a",
        "inverse-surface": "#2b2119",
        "inverse-on-surface": "#fbf6ee",
        outline: "#9a8774",
        "outline-variant": "#e4d7c4",
        "surface-tint": "#2f5d46",
        primary: "#2f5d46",
        "on-primary": "#fffcf7",
        "primary-container": "#3f7a5c",
        "on-primary-container": "#fffcf7",
        "inverse-primary": "#f2b23e",
        secondary: "#a4502c",
        "on-secondary": "#fffcf7",
        "secondary-container": "#f8dccd",
        "on-secondary-container": "#6e3219",
        tertiary: "#7a5a14",
        "on-tertiary": "#fffcf7",
        "tertiary-container": "#fbe6b0",
        "on-tertiary-container": "#4d3806",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#fbe3a8",
        "primary-fixed-dim": "#f2b23e",
        "on-primary-fixed": "#3a2a05",
        "on-primary-fixed-variant": "#5f4510",
        "secondary-fixed": "#f8dccd",
        "secondary-fixed-dim": "#eebfa6",
        "on-secondary-fixed": "#2b2119",
        "on-secondary-fixed-variant": "#6e3219",
        "tertiary-fixed": "#efe4d0",
        "tertiary-fixed-dim": "#d9c9ad",
        "on-tertiary-fixed": "#2b2119",
        "on-tertiary-fixed-variant": "#55483a",
        background: "#fbf6ee",
        "on-background": "#2b2119",
      },
      borderRadius: {
        DEFAULT: "0.375rem",
        sm: "0.25rem",
        md: "0.5rem",
        lg: "0.625rem",
        xl: "0.875rem",
        full: "9999px",
      },
      spacing: {
        unit: "8px",
        gutter: "24px",
        "margin-mobile": "20px",
        "margin-desktop": "64px",
        "container-max": "1200px",
      },
      maxWidth: {
        "container-max": "1200px",
      },
      fontFamily: {
        "display-xl": ["var(--font-display)", "Bricolage Grotesque", "ui-sans-serif", "sans-serif"],
        "headline-lg": ["var(--font-display)", "Bricolage Grotesque", "ui-sans-serif", "sans-serif"],
        "headline-lg-mobile": ["var(--font-display)", "Bricolage Grotesque", "ui-sans-serif", "sans-serif"],
        "body-rt": ["var(--font-body)", "Figtree", "ui-sans-serif", "sans-serif"],
        "body-sm": ["var(--font-body)", "Figtree", "ui-sans-serif", "sans-serif"],
        "code-md": ["var(--font-jbm)", "JetBrains Mono", "monospace"],
        sans: ["var(--font-body)", "Figtree", "ui-sans-serif", "sans-serif"],
        mono: ["var(--font-jbm)", "JetBrains Mono", "monospace"],
      },
      fontSize: {
        "body-sm": ["14px", { lineHeight: "1.5", letterSpacing: "0", fontWeight: "400" }],
        "code-md": ["14px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-rt": ["17px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "display-xl": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

export default config;
